## 梯度下降法的向量化

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
boston = datasets.load_boston()
X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
from ML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, seed=666)

## [向量化code](ML/LinearRegression.py)

In [4]:
from ML.LinearRegression import LinearRegression

lin_reg1 = LinearRegression()
%time lin_reg1.fit_normal(X_train, y_train)
lin_reg1.score(X_test, y_test)

Wall time: 67.9 ms


0.8129794056212895

In [5]:
lin_reg1.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

## 梯度下降法

In [6]:
lin_reg2 = LinearRegression()
lin_reg2.fit_gd(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
E:\code\py\ML\06-梯度下降法\ML\LinearRegression.py:37: RuntimeWarning: overflow encountered in square
  return np.sum((y - X_b.dot(theta)) ** 2) / len(y)
E:\code\py\ML\06-梯度下降法\ML\LinearRegression.py:59: RuntimeWarning: invalid value encountered in double_scalars
  if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):


LinearRegression()

In [7]:
lin_reg2.coef_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

## 由于X_train较大，计算出的数据较大，不收敛

In [8]:
lin_reg2.fit_gd(X_train, y_train, eta=0.000001)

LinearRegression()

In [9]:
lin_reg2.coef_

array([-0.10245704,  0.11535876, -0.06248791,  0.00207516,  0.00447152,
        0.11954208,  0.04684195,  0.03460927, -0.00452122,  0.00324507,
        0.1271939 ,  0.04484862, -0.22542441])

In [10]:
lin_reg2.score(X_test, y_test)

0.2758681872447726

In [11]:
%time lin_reg2.fit_gd(X_train, y_train, eta=0.000001, n_iters=1e6)

Wall time: 1min 15s


LinearRegression()

In [12]:
lin_reg2.coef_

array([-1.07889200e-01,  5.91494760e-02, -5.72920411e-02,  1.19334353e-01,
        2.07223623e-01,  3.91254775e+00,  1.50564949e-03, -5.36511902e-01,
        1.13424276e-01, -9.76209406e-03,  5.35544815e-02,  1.58440412e-02,
       -3.78786162e-01])

In [15]:
lin_reg2.score(X_test, y_test)

0.7542932581943915

### 使用梯度下降法前进行数据归一化

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
standScaler = StandardScaler()
standScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
X_train_strandard = standScaler.transform(X_train)

In [19]:
lin_reg3 = LinearRegression()
%time lin_reg3.fit_gd(X_train_strandard, y_train)

Wall time: 320 ms


LinearRegression()

In [20]:
X_test_standard = standScaler.transform(X_test)

In [21]:
lin_reg3.score(X_test_standard, y_test)

0.8129873310487505

### 梯度下降法的优势

In [28]:
m = 10000
n = 5000

big_X = np.random.normal(size=(m, n))
true_theta = np.random.uniform(0.0, 100.0, size=n+1)
big_y = big_X.dot(true_theta[1:]) + true_theta[0] + np.random.normal(0., 10., size=m)

In [29]:
%time lin_reg1.fit_normal(big_X, big_y)

Wall time: 18.4 s


LinearRegression()

In [30]:
%time lin_reg2.fit_gd(big_X, big_y)

Wall time: 11min 23s


LinearRegression()