## 02 scikit-learn中的kNN

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [47]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])
x = x.reshape(1,-1)

In [48]:
%run kNN_function/kNN_simple.py

In [49]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y

1

# sklearn 调用

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [23]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [36]:
x = x.reshape(1,-1)
x

array([[8.09360732, 3.36573151]])

In [50]:
kNN_classifier.predict(x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1])

# 调用整理后的封装

In [52]:
%run kNN_function/KNN.py

In [53]:
knn_clf = KNNClassifier(k=6)

In [54]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [56]:
X_predict = x

In [57]:
y_predict = knn_clf.predict(X_predict)
y_predict

array([1])